[package]
name = "inkmark-parse"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
pulldown-cmark.workspace = true
inkmark-buffer.workspace = true

[dev-dependencies]
criterion.workspace = true
inkmark-bench.workspace = true
proptest = "1.11.0"
serde_json = "1.0.151"

[[bench]]
name = "parse"
harness = false
