[package]
name = "inkmark-buffer"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
regex-cursor.workspace = true
ropey.workspace = true

[dev-dependencies]
criterion.workspace = true
inkmark-bench.workspace = true
proptest = "1.11.0"
tempfile = "3.27.0"

[[bench]]
name = "buffer"
harness = false
