[package]
name = "inkmark-view"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
unicode-width.workspace = true
egui.workspace = true
image.workspace = true
inkmark-buffer.workspace = true
inkmark-files.workspace = true
inkmark-minimap.workspace = true
inkmark-parse.workspace = true
inkmark-text.workspace = true
unicode-segmentation.workspace = true

[dev-dependencies]
tempfile = "3.27.0"
